'use client'

import { FormEvent, useState } from 'react'
import { LogIn } from 'lucide-react'

type AuthScreenProps = { mode: 'login' | 'register'; registered: boolean; error: string; loading: boolean; onRegistered: (name: string, email: string, password: string, phoneNumber: string) => void; onLogin: (email: string, password: string) => void; onRegister: () => void }

export default function AuthScreen({ mode, registered, error, loading, onRegistered, onLogin, onRegister }: AuthScreenProps) {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [phoneNumber, setPhoneNumber] = useState('')
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mode === 'login' ? onLogin(email, password) : onRegistered(name, email, password, phoneNumber) }
  return <main className="grid min-h-screen lg:grid-cols-2"><div className="relative hidden overflow-hidden bg-[#171419] lg:block"><img src="https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=85" alt="Cinema seats" className="h-full w-full object-cover opacity-50" /><div className="absolute inset-0 bg-gradient-to-br from-[#0b0b0f] via-transparent to-[#ff5b36]/20" /><div className="absolute left-12 top-12 font-display text-xl font-bold">reel<span className="text-[#ff5b36]">tick</span></div><div className="absolute bottom-16 left-12"><p className="text-sm uppercase tracking-[.25em] text-[#ff8a6c]">Cinema, curated</p><h1 className="mt-4 font-display text-5xl font-bold leading-none">Make tonight<br />a story.</h1></div></div><div className="flex items-center justify-center bg-[#0b0b0f] p-6"><div className="w-full max-w-[390px]"><p className="text-sm text-[#ff8a6c]">{mode === 'login' ? 'Welcome back' : 'Join the club'}</p><h1 className="mt-2 font-display text-4xl font-bold">{mode === 'login' ? 'Sign in to continue' : 'Create your account'}</h1>{registered && mode === 'login' && <div className="mt-5 rounded-lg border border-[#78b996]/30 bg-[#78b996]/10 p-3 text-sm text-[#a9d7bc]">Account created. You can sign in now.</div>}{error && <p className="mt-5 rounded-lg border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}<form className="mt-8 space-y-4" onSubmit={submit}>{mode === 'register' && <input required value={name} onChange={event => setName(event.target.value)} placeholder="Full name" className="auth-input" />}<input required value={email} onChange={event => setEmail(event.target.value)} type="email" placeholder="Email address" className="auth-input" />{mode === 'register' && <input required value={phoneNumber} onChange={event => setPhoneNumber(event.target.value)} placeholder="Phone number" className="auth-input" />}<input required value={password} onChange={event => setPassword(event.target.value)} type="password" placeholder="Password" className="auth-input" /><button disabled={loading} className="mt-2 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#ff5b36] text-sm font-bold text-[#1b100d] disabled:opacity-50">{mode === 'login' ? <><LogIn size={16} /> {loading ? 'Signing in...' : 'Sign in'}</> : loading ? 'Creating account...' : 'Create account'}</button></form><p className="mt-7 text-center text-sm text-[#89847f]">{mode === 'login' ? <>New to reeltick? <button onClick={onRegister} className="font-semibold text-[#ff8a6c]">Create an account</button></> : <>Already have an account? <button onClick={onRegister} className="font-semibold text-[#ff8a6c]">Sign in</button></>}</p></div></div></main>
}
